### ISSUE TITLE
Where are feature files with tests?

### ISSUE THREAD

**Issue by apetrenko-planeks** [reportportal/agent-js-cucumber#101]
It does not look as for cucumber. Hooks are absent. Is it example for cucumber?

**Comment by AmsterGet** [comment]
Hello @apetrenko-planeks !
If you mean the example of how this reporter works with cucumber tests, you can follow the [example repo link](https://github.com/reportportal/examples-js/tree/master/example-cucumber).

**Comment by AmsterGet** [comment]
I'll close the issue. Feel free to open the new one in case of any questions.
