### ISSUE TITLE
Cucumber JS Version 8 support

### ISSUE THREAD

**Issue by scottwalter-nice** [reportportal/agent-js-cucumber#102]
Hi,

Are there plans to support later versions of Cucumber JS?   Right now the plugin only supports up to version 6.x while 8.x is the current version of Cucumber JS

**Comment by AmsterGet** [comment]
Hello @scottwalter-nice !
The new cucumber package support is under implementation now.
Please refer the details in [this issue](https://github.com/reportportal/agent-js-cucumber/issues/94).
I'll close the issue as duplicate.
