### ISSUE TITLE
Support for Cucumberjs  new version(cucumber3 and cucumber 4)

### ISSUE THREAD

**Issue by Balajiiguru** [reportportal/agent-js-cucumber#11]
Do you have plan to extend this plugin support for cucumber new version?

**Comment by DzmitryHumianiuk** [comment]
@filland could you please verify agent against cucumberJS v5.0+?

**Comment by filland** [comment]
@DzmitryHumianiuk sure

**Comment by filland** [comment]
@Balajiiguru i tried to run examples using 5th version of cucumber and it worked. So you can try to use current released version of cucumber agent.

**Comment by filland** [comment]
@Balajiiguru Current version should work with 3rd and 4th versions of cucumber. Also i tried to run examples using 5th version of cucumber js and it worked. So you can try to use current version of cucumber agent.

**Comment by filland** [comment]
@Balajiiguru Current version should work with 3rd and 4th versions of cucumber. Also i tried to run examples using 5th version of cucumber js and it worked. 
So, you can try to use current version of cucumber agent for 3, 4 and 5th versions.

**Comment by npopov-d3** [comment]
If it works, could you push a new version to NPM please?

**Comment by filland** [comment]
@npopov-d3 it is already published
https://www.npmjs.com/package/reportportal-agent-cucumber

**Comment by vhildebrandt-usa** [comment]
@filland or @DzmitryHumianiuk: I'm using similar packages (same major versions) like in issue [15](https://github.com/reportportal/agent-js-cucumber/issues/15) but I still get this error:
E/launcher - Error: TypeError: this.registerHandler is not a function
    at Object.reportPortalHandlers (C:\Users\Viktor\source\repos\CMACS\CMACS\ClientApp\node_modules\agent-js-cucumber\modules\cucumber-epam-reportportal-handler.js:38:10)

This are my verions:
"reportportal-agent-cucumber": "^2.0.6",

"agent-js-cucumber": "^0.1.1",
"cucumber": "^5.1.0",
"protractor": "~5.4.0",
   "protractor-cucumber-framework": "^6.1.3"

Am I missing something?

**Comment by DzmitryHumianiuk** [comment]
@vhildebrandt-usa this agent is not supported for a while.
we will update it to version 5, once finish with v5 release

**Comment by vhildebrandt-usa** [comment]
Thanks @DzmitryHumianiuk for response. Do you have a plan when are you going to do that? This year?
What exactly the agent-js-cucumber version?

**Comment by DzmitryHumianiuk** [comment]
@vhildebrandt-usa we have dedicated engineer for this now.
@HardNorth will work on all agents next weeks.
we plan to update all JAVA related agents + scala right to v5.0 public release.
JS will be the next scope.

**Comment by AutomationSpecialist** [comment]
@DzmitryHumianiuk Has there been any update on the integration of reportportal with version 5?

**Comment by DzmitryHumianiuk** [comment]
JS in progress at the moment.
next week planned to cover the rest of js agents

**Comment by AutomationSpecialist** [comment]
Thanks @DzmitryHumianiuk for your response. Please update when you release the new version. Eagerly waiting for it.

**Comment by DzmitryHumianiuk** [comment]
@AutomationSpecialist can you please enlighten me with a little information from JS world?
how many active version of JS Cucumber exists?

is it just JS Cucumber, or JS Cucumber2, JS Cucumber3 and JS Cucumber4 are also valid?

**Comment by AutomationSpecialist** [comment]
@DzmitryHumianiuk Sorry for the late reply. I think all are active and the latest version is cucumber js 6. I think it will be enough if report portal can support cucumber 3 and above as Cucumber JS 3 had some big changes.

**Comment by AmsterGet** [comment]
Hi @AutomationSpecialist !
Sorry for the late notification.
Now we have [`@reportportal/agent-js-cucumber`](https://www.npmjs.com/package/@reportportal/agent-js-cucumber) with RP 5.0 full compatibility.
This agent also supports cucumber versions 4.x - 6.x.
So I will close this question. Feel free reopen it if you have any other questions on the topic.
