### ISSUE TITLE
DEBUG mode in the config file does not report to Debug

### ISSUE THREAD

**Issue by MatanNoachNice** [reportportal/agent-js-cucumber#130]
Hi,

I am trying to make reports that project members running locally reach the DEBUG section in the report portal, but the "mode":"DEBUG" in the config file does not seem to work, and the tests are still presented in the Launches section.

I am using the examples-js repository as an example and running "simpleTest". I updated the config file like this:

```
{
  "token": "{my_token}",
  "endpoint": "{my_endpoint}/api/v1",
  "launch": "cucumber-js-test",
  "project": "{my_project}",
  "mode": "DEBUG",
  "attributes": [
    {
      "key": "launchK",
      "value": "launchV"
    }
  ],
  "description": "DESCRIPTION"
}
```
And the results look like this:
![image](https://user-images.githubusercontent.com/95622894/219934699-b23cb8bc-dc21-4e3a-8241-e6fee0daafb3.png)

Am I missing something?

P.S. I also turned the "debug": true flag, but the results are the same

**Comment by Bam6ycha** [comment]
@MatanNoachNice, Hello there!
We released a new version of Agent. In that version, this issue was fixed.

**Comment by MatanNoachNice** [comment]
Thanks @Bam6ycha. It works now!
