### ISSUE TITLE
reportportal/agent-js-cucumber 5.2.1 incomprtible with Cucumber 9.2.0

### ISSUE THREAD

**Issue by TimTim757** [reportportal/agent-js-cucumber#147]
npm ERR!   @cucumber/cucumber@"9.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @cucumber/cucumber@"7.x - 8.x" from @reportportal/agent-js-cucumber@5.2.1

**Comment by AmsterGet** [comment]
Hello @TimTim757 !
Thanks for the issue!
We need to check compatibility with cucumber@9 and then release a new version of the agent.
There is no ETA, but we will try to make it work as soon as possible in accordance with our priorities.
By the way, any PR and contributions are welcome :)

**Comment by AmsterGet** [comment]
Hi @TimTim757 !
Cucumber 9.x support released with agent version 5.2.2.
