### ISSUE TITLE
Drop cucumber  < 6 support

### ISSUE THREAD

**Issue by dayofr** [reportportal/agent-js-cucumber#153]
Hi,

due to the current devDependencies, cucumber 6.x is installed alongside @cucumber/cucumber 9.x

`"peerDependencies": {
    "cucumber": "4.x - 6.x",
    "@cucumber/cucumber": "7.x - 9.x"
  },`

Could it be possible to drop support for cucumber < 7.x ?

**Comment by AmsterGet** [comment]
Hi @rutika89 !
Done in the scope of [release 5.3.0](https://github.com/reportportal/agent-js-cucumber/releases/tag/v5.3.0).
