### ISSUE TITLE
reportportal/agent-js-cucumber 5.2.2 incomprtible with Cucumber 10.0.2

### ISSUE THREAD

**Issue by rutika89** [reportportal/agent-js-cucumber#155]
┬ @reportportal/agent-js-cucumber 5.2.2
  ├── ✕ missing peer cucumber@"4.x - 6.x"
  └── ✕ unmet peer @cucumber/cucumber@"7.x - 9.x": found 10.2.1

**Comment by AmsterGet** [comment]
Hi @rutika89 !
Thanks for pointing this out, we are working on the new CucumberJS version support for this package.
I'll update this thread once its ready,

**Comment by AmsterGet** [comment]
Hi @rutika89 !
Done in the scope of [release 5.3.0](https://github.com/reportportal/agent-js-cucumber/releases/tag/v5.3.0).
