### ISSUE TITLE
Support for @cucumber/cucumber 11.x

### ISSUE THREAD

**Issue by lcharlois-neotys** [reportportal/agent-js-cucumber#169]
Hello,

At the moment the agent is not compatible with @cucumber/cucumber 11.x.

It would be nice to support it.

**Comment by AmsterGet** [comment]
Added in the scope of [Release 5.5.0](https://github.com/reportportal/agent-js-cucumber/releases/tag/v5.5.0).

**Comment by lcharlois-neotys** [comment]
Wow, you're so fast.
Thanks.
