### ISSUE TITLE
RP server returning name too long errors with the latest client

### ISSUE THREAD

**Issue by npopov-d3** [reportportal/agent-js-cucumber#22]
Just gave new reportportal-agent-cucumber (2.0.6) a go, and got some weird results.
Some of my features are working fine, but others get rejected by RP server (4.2.2) like so:
`(node:95882) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 68): Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'name' should have size from '1' to '256'.] "}`
Visually what this does is the step never finishes, and later tests/steps start throwing new errors like 
`Error: Request failed with status code 406: {"error_code":40022,"message":"Finish test item is not allowed. Test item '5cba100da7b11b0001ae3ee3' has descendants with 'IN_PROGRESS' status.`

The features that fail have steps which take json strings as params, so they can easily exceed 256 characters.
`"reportportal-agent-cucumber": "^2.0.6", "cucumber": "^4.2.1"` RP 4.2.2

p.s. I just realized its a problem with report portal and cucumber in general, not the latest version vs the old one.. Basically cucumber allows you to pass data from example tables which becomes part of the step name, but RP rejects anything over 256ch long.

**Comment by AmsterGet** [comment]
Hi @npopov-d3 !
Sorry for the late notification.
Now we have [`@reportportal/agent-js-cucumber`](https://www.npmjs.com/package/@reportportal/agent-js-cucumber) with RP 5.0 full compatibility.
So I will close this question. Feel free reopen it if you have any other questions on the topic.
