### ISSUE TITLE
report portal agent only provides step wise test  results on report portal launches view.Scenario level pass fail count not supported.

### ISSUE THREAD

**Issue by Vidhilika** [reportportal/agent-js-cucumber#27]

**Comment by evjlobanova** [comment]
@Vidhilika Could you please clarify your request?

**Comment by evjlobanova** [comment]
Please create a new issue in accordence with  provided form

**Comment by evjlobanova** [comment]
**Describe the bug**
...

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]
