### ISSUE TITLE
Wrong Scenarios Count Bug

### ISSUE THREAD

**Issue by jacob-hanbeen-kim** [reportportal/agent-js-cucumber#36]
**_cucumber-reportportal-formatter_** seems to have a bug where the **context.scenariosCount** is wrong when there are examples for the scearnio.

**Exact Location**
line 225 under the **onPickleAccepted** function.

**Current Implementation**
`context.scenariosCount[featureUri] = { total: featureDocument.children.length, done: 0 };`

**Proposed/Possible Fix**
`let total = featureDocument.children.length;
        featureDocument.children.forEach(child => {
          child.examples.forEach(ex => {
            total += ex.tableBody.length - 1;
          })
        })
        context.scenariosCount[featureUri] = { total: total, done: 0 };`

Original implementation may have been working for simple examples where the step def doesn't have actual http request that requires async/await functions. The way current count is implemented, it will close the feature file after the first example since "total == done", which will throw an item not found error. Scenarios count needs to account for examples, since 3 example means I will be running the same scenario 3 times.

**Comment by jacob-hanbeen-kim** [comment]
update. Need to check if child.example is undefined first for scenarios which doesn't have examples

**Comment by DiscoElevator** [comment]
Hello, @jacob-hanbeen-kim 
Thanks for your finding! Could you please create a PR with your fix along with a small example to check?

**Comment by DzmitryHumianiuk** [comment]
@jacob-hanbeen-kim ?

**Comment by jacob-hanbeen-kim** [comment]
I will, but I just found another factor that might impact the count. Feature children includes background which is really not a scenario. Current formatter also doesn't work with background. I'll open another bug for that.
