### ISSUE TITLE
Unable to execute the sample project. Getting status code 400

### ISSUE THREAD

**Issue by saravanan-autodev** [reportportal/agent-js-cucumber#41]
When i tried to execute the sample project given in the examples folder. Getting 400 error code from report portal.

Error in Console:
npm run example:simple

> reportportal-agent-cucumber@2.0.6 example:simple Z:\Downloads\agent-js-cucumber-master\agent-js-cucumber-master
> cd examples && npm run simpleTest

> @ simpleTest Z:\Downloads\agent-js-cucumber-master\agent-js-cucumber-master\examples
> cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js

**Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}**
    at Z:\Downloads\agent-js-cucumber-master\agent-js-cucumber-master\node_modules\reportportal-client\lib\rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:964) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at Z:\Downloads\agent-js-cucumber-master\agent-js-cucumber-master\node_modules\reportportal-client\lib\rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not
handled will terminate the Node.js process with a non-zero exit code.

Could you help to resolve this.Thanks.

**Comment by DiscoElevator** [comment]
Hello, @saravanan-autodev 
This agent is not yet released for RP v5, but you can install it from the master branch if you need.

**Comment by saravanan-autodev** [comment]
Hello @DiscoElevator 
This is the version which is deployed 4.1.0. Could you please let me know if this agent is supported for this version of report portal.
![image](https://user-images.githubusercontent.com/62570501/78811784-031fa300-79e8-11ea-9a9b-a04334c608c4.png)

**Comment by DiscoElevator** [comment]
Looks like it's because of broken backward compatibility in the reportportal-client.
As a workaround, you can install reportportal-client version 5.2.3.
Please let me know it it helped.

**Comment by saravanan-autodev** [comment]
@DiscoElevator - Hey, Thanks much. It helped, now i am able to run the sample report provided the the module. Thanks.
