### ISSUE TITLE
TypeError: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by FMSoftwareio** [reportportal/agent-js-cucumber#43]
`TypeError: Cannot read property 'text' of null
    at CucumberReportPortalFormatter.onTestStepStarted (/Users/cfletcher/repos/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:348:33)
    at EventEmitter.emit (events.js:315:20)`

I've come across this issue in my own test repo and it seems to be related to how the feature files are named and/or some combination of the tags included. The formatter continues to report the error above until I change the name of the feature file or remove it from the directory.

Note: There is nothing wrong with the cucumber files or gherkin. If you remove the formatter, all the tests will run as expected.

I was successful in reproducing this behavior using the examples folder:
1. cd examples
2. npm run allTests
3. observe error above is reported
4. remove the webdriver_integration.feature file
5. re-run npm tests
6. observe error is no longer present

**Comment by AmsterGet** [comment]
Fixed in https://github.com/reportportal/agent-js-cucumber/pull/46
