### ISSUE TITLE
NPM module has stale version, installing from github crashes reportportal

### ISSUE THREAD

**Issue by jlundy2** [reportportal/agent-js-cucumber#56]
So running `npm install reportportal-agent-cucumber`  installs a module that hasn't been published in a year and doesn't conform to the examples listed.
Running a test suite results in the report portal api getting overloaded and the reportportal application crashes.
This is occurring on report portal 5.2.0.

**Comment by AmsterGet** [comment]
Hi @jlundy2!
In the coming days we will publish a new version for `agent-js-cucumber`, compatible with RP 5.*.
Now as a workaround you can install the latest agent updates directly from GitHub:
```
npm install https://github.com/reportportal/agent-js-cucumber#master
```

I'll close the issue, feel free to open it again if you have any other questions on this topic.
