### ISSUE TITLE
Getting Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] 

### ISSUE THREAD

**Issue by lakshminagandla2678** [reportportal/agent-js-cucumber#63]
Hi All,

Today I have tried to integrate Report portal with TestCafe CucumberJS framework. We are getting below error in terminal while we are executing the code and report portal not getting updated too.  

Can any one help me to resolve this issue to update my log messages in report portal

PS C:\Users\lakshmi.nagandla\Downloads\testcafe-cucumber-master> ./node_modules/.bin/cucumber-js.cmd --format ./reportPortalFormatter.js
Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at C:\Users\lakshmi.nagandla\Downloads\testcafe-cucumber-master\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10364) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at C:\Users\lakshmi.nagandla\Downloads\testcafe-cucumber-master\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10364) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at C:\Users\lakshmi.nagandla\Downloads\testcafe-cucumber-master\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:10364) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at C:\Users\lakshmi.nagandla\Downloads\testcafe-cucumber-master\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
 Running tests in:
 - Chrome 84.0.4147.135 / Windows 10

 fixture
(node:10364) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
(node:10364) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
(node:10364) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 16)
(node:10364) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 18)
 × test

   1) Unhandled promise rejection:

      Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
      at C:\Users\lakshmi.nagandla\Downloads\testcafe-cucumber-master\node_modules\@reportportal\client-javascript\lib\rest.js:31:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by AmsterGet** [comment]
Hi @lakshminagandla2678 !
Are you using our [agent-js-cucumber](https://github.com/reportportal/agent-js-cucumber) integration or trying to create your own integration using [client-javascript](https://github.com/reportportal/client-javascript)?

**Comment by lakshminagandla2678** [comment]
Hi @AmsterGet 

Am not using my own integration, and am just using agent-js-cucumber libraray from npm package and trying to integrate with report portal with help of testcafe-cucumberjs framework.  

Note: I have used below to download the agent-js-cucumber library

npm install --save-dev @reportportal/agent-js-cucumber

**Comment by ddymau** [comment]
I have the same problem
using:
 "devDependencies": {
    "@reportportal/agent-js-cucumber": "^5.0.0",
    "cucumber": "^6.0.5",
    "electron": "^9.0.0"
  },
  "dependencies": {
    "chai": "^4.2.0",
    "chromedriver": "^85.0.0",
    "cucumber-assert": "^2.0.1",
    "dotenv": "^8.2.0",
    "electron-chromedriver": "^10.0.0",
    "electron-single-instance": "0.0.2",
    "selenium-webdriver": "^4.0.0-alpha.7",
    "spectron": "10.0.1"
  }

**Comment by AmsterGet** [comment]
Hi All!
Please refer to the following [issue](https://github.com/reportportal/client-javascript/issues/96).

**Comment by AmsterGet** [comment]
As described in the above issue, the issue was caused by RP and agent version mismatch.
