### ISSUE TITLE
Incorrect Test status in case of all steps passed 

### ISSUE THREAD

**Issue by Malahovskys** [reportportal/agent-js-cucumber#66]
Test is marked as failed and To Investigate.

STR:
1. Clone https://github.com/reportportal/examples-js/tree/master/example-cucumber
2. Specify correct data config/rpConfig.json (instance of the Report Portal is https://reportportal.epam.com/).
3. npm install
4. npm install cucumber@6 --no-save
5. npm run example:simple
Result:

> @ example:simpleTest C:\Users\XXX\examples-js-master\example-cucumber
> cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ example:simpleTest: `cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ example:simpleTest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2020-10-02T11_09_40_613Z-debug.log

[2020-10-02T11_09_40_613Z-debug - Sanitazed.log](https://github.com/reportportal/agent-js-cucumber/files/5317534/2020-10-02T11_09_40_613Z-debug.-.Sanitazed.log)

**Comment by Ranazya** [comment]
Hey @Malahovskys 

This pull request has fixed this bug https://github.com/reportportal/agent-js-cucumber/pull/64
It's just waiting for a review
