### ISSUE TITLE
upgrade the agent-js-cucumber to support @cucumber/cucumber

### ISSUE THREAD

**Issue by Rajkumar502** [reportportal/agent-js-cucumber#94]
@reportportal/agent-js-cucumber is not supporting currently for @cucumber/cucumber, need an upgrade to fix this issue

**Comment by AmsterGet** [comment]
Looks similar to https://github.com/reportportal/agent-js-cucumber/issues/86

**Comment by eugenefurs** [comment]
any progress on it?

**Comment by OnyinyeAladiume22** [comment]
Has there been any update?

**Comment by AmsterGet** [comment]
Hello guys!

We have started implementing support for the new cucumber package, but now it is not at the active stage.

Next week I'll go over what else we need to get it published and provide details to this issue.

Stay tuned.

**Comment by OnyinyeAladiume22** [comment]
@AmsterGet Any update?

**Comment by AmsterGet** [comment]
Hi @OnyinyeAladiume22 !
I rechecked what we did to support the new cucumber package.
It's not ready yet. I will update the backlog with tasks and we will try to take it in the upcoming sprints.
I'll report progress here and provide release date information as soon as it's known.

**Comment by OnyinyeAladiume22** [comment]
Hi @AmsterGet, just wanted to follow up again and see if you can give us an estimated delivery date on when the agent will support the new cucumber package?

**Comment by AmsterGet** [comment]
Hi @OnyinyeAladiume22 !
At the moment the approximate ETA is the middle of November.
It may take fewer in case the team will finish RP 5.7.3 release in time without unexpected issues.

**Comment by OnyinyeAladiume22** [comment]
@AmsterGet Is there any update?

**Comment by AmsterGet** [comment]
Hello @OnyinyeAladiume22 !
We've just released the version 5.1.0.
Please check [it out](https://www.npmjs.com/package/@reportportal/agent-js-cucumber).
And we welcome your feedback to fix issues as soon as possible if they occur :)
